#!/bin/bash

NEW_USER=$(cat /etc/passwd | grep "/home" |cut -d: -f1 |head -1)
INSTALL_OPTION=""

# Any failed command will just be skiped, error message may pop up but won't crash the install process

# Net-install creates the file /tmp/run_once in live environment (need to be transfered to installed system) so it can be used to detect install option


_check_internet_connection(){
    ping -c 1 8.8.8.8 >& /dev/null   # ping Google's address
}

_arch_news_latest_headline(){
    # gets the latest Arch news headline for 'kalu' config file news.conf
    local info=$(mktemp)
    wget -q -T 10 -O $info https://www.archlinux.org/ && \
        { grep 'title="View full article:' $info | sed -e 's|&gt;|>|g' -e 's|^.*">[ ]*||' -e 's|</a>$||' | head -n 1 ; }
    rm -f $info
}

_config_for_app(){
    # handle configs for apps here; called from distro specific function

    local app="$1"    # name of the app

    case "$app" in
        kalu)
            mkdir -p /etc/skel/.config/kalu
            printf "Last=" >> /etc/skel/.config/kalu/news.conf
            _arch_news_latest_headline >> /etc/skel/.config/kalu/news.conf
            ;;
        update-mirrorlist)
            test -x /usr/bin/$app && {
                /usr/bin/$app
            }
            ;;
        # add other apps here!
        *)
            ;;
    esac
}

_vbox(){

    # Detects if running in vbox

    local _vbox_packages=(virtualbox-guest-utils virtualbox-guest-modules-arch)   # manuel: made it a local variable
    local xx

    lspci | grep -i "virtualbox" >/dev/null
    if [[ $? == 0 ]]                                  # manuel: is this test reversed???
    then
        if [ -d /tmp/run_once ]                       # manuel: what is the test and purpose? File existence test is -f
        then
            for xx in ${_vbox_packages[*]}
            do pacman -S $xx --noconfirm
            done
        fi   
        : 
    else
        for xx in ${_vbox_packages[*]} ; do
            test -n "$(pacman -Q $xx 2>/dev/null)" && pacman -Rnsdd $xx --noconfirm
        done
        rm -f /usr/lib/modules-load.d/virtualbox-guest-dkms.conf
    fi
}

_common_systemd(){
    # ARRAY
    local _systemd_enable=(NetworkManager vboxservice org.cups.cupsd avahi-daemon gdm lightdm sddm)   # manuel: local var
    # ARRAY
    local _systemd_disable=(multi-user.target pacman-init)                                            # manuel: local var

    local xx
    for xx in ${_systemd_enable[*]}; do systemctl enable -f $xx; done

    local yy
    for yy in ${_systemd_disable[*]}; do systemctl disable -f $yy; done
}

_sed_stuff(){

    # Journal
    sed -i 's/volatile/auto/g' /etc/systemd/journald.conf 2>>/tmp/.errlog
    sed -i 's/.*pam_wheel\.so/#&/' /etc/pam.d/su
}

_clean_archiso(){

    # ARRAY
    local _files_to_remove=(                               # manuel: local var
        /etc/sudoers.d/g_wheel
        /var/lib/NetworkManager/NetworkManager.state
        /etc/systemd/system/{choose-mirror.service,pacman-init.service,etc-pacman.d-gnupg.mount,getty@tty1.service.d}
        /etc/systemd/scripts/choose-mirror
        /etc/systemd/system/getty@tty1.service.d/autologin.conf
        /root/{.automated_script.sh,.zlogin}
        /etc/mkinitcpio-archiso.conf
        /etc/initcpio
        /etc/udev/rules.d/81-dhcpcd.rules
        /usr/bin/{calamares_switcher,cleaner_script.sh}
        /home/$NEW_USER/.config/qt5ct
        /home/$NEW_USER/{.xinitrc,.xsession}
        /root/{.xinitrc,.xsession}
        /etc/skel/{.xinitrc,.xsession}
    )

    local xx

    for xx in ${_files_to_remove[*]}; do rm -rf $xx; done

    find /usr/lib/initcpio -name archiso* -type f -exec rm '{}' \;

}

_endeavouros(){

    sed -i "/if/,/fi/"'s/^/#/' /home/$NEW_USER/.bash_profile
    sed -i "/if/,/fi/"'s/^/#/' /root/.bash_profile

    pacman -R gnome-software --noconfirm
    pacman -Rsc gnome-boxes --noconfirm

    _check_internet_connection && {
        #_config_for_app update-mirrorlist # calamares does it for offline/online install
        _config_for_app kalu
    }

}

_check_install_mode(){

    # manuel: I'd rewrite this a bit to be clearer:

    # if [ ! d = "/tmp/run_once" ]; then INSTALL_OPTION="OFFLINE_MODE"; else INSTALL_OPTION="ONLINE_MODE"; fi      # manuel: d should be -f ?

    if [ -f /tmp/run_once ] ; then
        INSTALL_OPTION="ONLINE_MODE"
    else
        INSTALL_OPTION="OFFLINE_MODE"
    fi

    # manuel: is some other code using variable INSTALL_OPTION? If not, it could be a local variable here.

    case "$INSTALL_OPTION" in
        OFFLINE_MODE)
                _clean_archiso
                _files_to_remove             # manuel: should be _clean_archiso intead?
                _sed_stuff
            ;;

        ONLINE_MODE)
                _implement_me_please
                # for now all systemd are enabled - can be specific offline/online in the future
            ;;
        *)
            ;;
    esac
}

########################################
########## SCRIPT STARTS HERE ##########
########################################

_check_install_mode
_common_systemd
_endeavouros
_vbox
rm -rf /usr/bin/{calamares_switcher,cleaner_script.sh}
