#!/bin/bash

NEW_USER=$(cat /etc/passwd | grep "/home" |cut -d: -f1 |head -1)

# Any failed command will just be skiped, error message may pop up but won't crash the install process

# Necessary for off/online
#_check_internet_connection
#_arch_news_latest_headline
#_config_for_app
#_common_systemd
#_clean_install_scripts
#_display_manager
#_endeavouros


# Offline
#_clean_archiso

# Online


#_vbox ????? should we purge calamares code?

# if [ ! -d $_reponame ]
# Check if using online install

# Check if package is installed
# DE, broadcom, nvidia detector etc

_check_internet_connection(){
    ping -c 1 8.8.8.8 >& /dev/null   # ping Google's address
}

_arch_news_latest_headline(){
    # gets the latest Arch news headline for 'kalu' config file news.conf
    local info=$(mktemp)
    wget -q -T 10 -O $info https://www.archlinux.org/ && \
        { grep 'title="View full article:' $info | sed -e 's|&gt;|>|g' -e 's|^.*">[ ]*||' -e 's|</a>$||' | head -n 1 ; }
    rm -f $info
}

_config_for_app(){
    # handle configs for apps here; called from distro specific function

    local app="$1"    # name of the app

    case "$app" in
        kalu)
            mkdir -p /etc/skel/.config/kalu
            printf "Last=" >> /etc/skel/.config/kalu/news.conf
            _arch_news_latest_headline >> /etc/skel/.config/kalu/news.conf
            ;;
        update-mirrorlist)
            test -x /usr/bin/$app && {
                /usr/bin/$app
            }
            ;;
        # add other apps here!
        *)
            ;;
    esac
}


_systemd_enable=(

NetworkManager
vboxservice
org.cups.cupsd
avahi-daemon
gdm
lightdm
sddm

)

_systemd_disable=(

multi-user.target
pacman-init

)

_common_systemd(){


local xx
for xx in ${_systemd_enable[*]}; do systemctl enable -f $xx; done

local yy
for yy in ${_systemd_disable[*]}; do systemctl disable -f $yy; done

}



_sed_stuff(){

# Journal
sed -i 's/volatile/auto/g' /etc/systemd/journald.conf 2>>/tmp/.errlog
sed -i 's/.*pam_wheel\.so/#&/' /etc/pam.d/su

}


_files_to_remove=(

/etc/sudoers.d/g_wheel
/var/lib/NetworkManager/NetworkManager.state
/etc/systemd/system/{choose-mirror.service,pacman-init.service,etc-pacman.d-gnupg.mount,getty@tty1.service.d}
/etc/systemd/scripts/choose-mirror
/etc/systemd/system/getty@tty1.service.d/autologin.conf
/root/{.automated_script.sh,.zlogin}
/etc/mkinitcpio-archiso.conf
/etc/initcpio
/etc/udev/rules.d/81-dhcpcd.rules
/usr/bin/{calamares_switcher,cleaner_script.sh}
/home/$NEW_USER/.config/qt5ct
/home/$NEW_USER/{.xinitrc,.xsession}
/root/{.xinitrc,.xsession}
/etc/skel/{.xinitrc,.xsession}

)

_clean_archiso(){

local xx

for xx in ${_files_to_remove[*]}; do rm -rf $xx; done

find /usr/lib/initcpio -name archiso* -type f -exec rm '{}' \;

}


_vbox(){

# Detects if running in vbox
local xx

lspci | grep -i "virtualbox" >/dev/null
if [[ $? == 0 ]]
    then
        :      
    else
        for xx in virtualbox-guest-utils virtualbox-guest-modules-arch virtualbox-guest-dkms ; do
            test -n "$(pacman -Q $xx 2>/dev/null)" && pacman -Rnsdd $xx --noconfirm
        done
        rm -f /usr/lib/modules-load.d/virtualbox-guest-dkms.conf
fi

}

_display_manager(){
# no problem if any of them fails

pacman -R gnome-software --noconfirm
pacman -Rsc gnome-boxes --noconfirm

}

_endeavouros(){

# what happens if we just delete the files, are they auto-created?

sed -i "/if/,/fi/"'s/^/#/' /home/$NEW_USER/.bash_profile
sed -i "/if/,/fi/"'s/^/#/' /root/.bash_profile

#_display_manager

_check_internet_connection && {
    #_config_for_app update-mirrorlist
    _config_for_app kalu
}

}



########################################
########## SCRIPT STARTS HERE ##########
########################################

_common_systemd
_clean_archiso
_endeavouros
