#!/bin/bash

# New script for using calamares.
#
# Note that this script can be called directly from the terminal,
# or it can be called from the Welcome app.

source /usr/share/endeavouros/scripts/eos-script-lib-yad || exit 1
#source /usr/share/endeavouros/scripts/translations.bash || exit 1

export -f eos_yad

DIE() {
    echo "$progname: warning: $mode: $1"
    exit 1
}

GUIDIE() {
    if [ 1 -eq 1 ] ; then
        local cmd=(
            eos_yad --form --title="Error"
            --text="$progname: warning: $mode: $1"
            --button=yad-quit
        )
        "${cmd[@]}"
    fi
    echo "$progname: warning: $mode: $1"
    exit 1
}


### Provides the install log contents. ###
FollowFile() {
    local tailfile="$1"
    local term_title="$2"
    local xpos="$3"
    local ypos="$4"

    xfce4-terminal -T "$term_title" --geometry=120x20+$xpos+$ypos -x tail -f "$tailfile" &
}

### Provides the pacman log. ###
CatchChrootedPacmanLog() {
    local pacmanlog=""
    local lockfile="$HOME/.$progname.lck"

    # wait until pacman.log is available in the chrooted system, then follow the log in background
    while true ; do
        sleep 2
        pacmanlog="$(/usr/bin/ls -1 /tmp/calamares-root-*/var/log/pacman.log 2>/dev/null | /usr/bin/tail -n 1)"
        if [ -n "$pacmanlog" ] ; then
            # pacman.log found
            [ -r "$lockfile" ] && return
            /usr/bin/touch "$lockfile"
            FollowFile "$pacmanlog" "Pacman log" 400 50
            break
        fi
    done
}

### Starts logging into the install log. ###
InstallLog_Start() {
    cat <<EOF > $log
########## $log by $progname
########## Started (UTC): $(date -u "+%x %X")
########## Install mode: $mode
EOF
    FollowFile "$log" "Install log" 20 20
}

### Starts calamares and makes it to run in the background. ###
Calamares_Start() {
    pkexec calamares -style kvantum -c /etc/calamares/ -d >> $log &
}

### Dialog that asks for the official or community edition. ###
AskMode() {
    local inet_no="Internet connection is not required"
    local inet_yes="Internet connection is required"
    local ret=0

    local txt=""

    txt+="Installing <b>EndeavourOS</b> to your system.\n\n"
    txt+="You can install one of the <i>official</i> editions, or one of the <i>community</i> editions.\n\n"
    txt+="<b>Official editions</b>: popular desktops made by the EndeavourOS team.\n"
    txt+="These editions include:\n<tt>"
    txt+="    Xfce\n"
    txt+="    KDE\n"
    txt+="    GNOME\n"
    txt+="    MATE\n"
    txt+="    LXQt\n"
    txt+="    Budgie\n</tt>"
    txt+="and more.\n"
    txt+="Official editions have a <i>vanilla theming</i>, and $inet_yes (online).\n\n"
    txt+="In addition to the above, you can install Xfce with a special <i>EndeavourOS theming</i>\n"
    txt+="and $inet_no (offline).\n\n"
    txt+="<b>Community editions</b>: editions made by the EndeavourOS community members.\n"
    txt+="Currently community editions include Sway and Bspwm. $inet_yes.\n"
    txt+="Note that the community edition will be selected a bit later, in Calamares.\n\n"

    local cmd=(
        eos_yad --form --title="Select what to install" --image=dialog-question
        --text="$txt"
        --button='Official (online)!!EndeavourOS team edition, vanilla theming, online install.':11
        --button='Official (offline)!!EndeavourOS team edition (Xfce), special theming, offline install.':13
        --button='Community!!EndeavourOS community edition, online install.':15
    )

    "${cmd[@]}"       # ask from the user

    ret=$?

    # prepare the settings (if $ret is OK)
    case "$ret" in
        11) mode=online ;;
        13) mode=offline ;;
        15) mode=community ;;
        252|*) ;; # DIE "selecting edition failed ($ret)." ;;
    esac
}

### Starts the calamares installer process and logging. ###
InstallWithLogs() {
    InstallLog_Start
    Calamares_Start

    if [ "$mode" != "offline" ] ; then
        CatchChrootedPacmanLog
    fi
}

CopyFile() {
    local filefrom="$1"   # source file
    local fileto="$2"     # destination file (not folder!)
    local folderto="$(dirname "$fileto")"

    [ -r "$filefrom" ] || GUIDIE "$FUNCNAME: file '$filefrom' does not exist."
    [ -d "$folderto" ] || GUIDIE "$FUNCNAME: folder '$folderto' does not exist."

    sudo cp $filefrom $fileto || GUIDIE "copying $filefrom to $fileto failed"
}

###  Runs the online install. ###
Online() {
    CopyFile $cfolder/settings_online.conf $cfolder/settings.conf
}

###  Runs the offline install. ###
Offline() {
    CopyFile $cfolder/settings_offline.conf $cfolder/settings.conf
}

###  Runs the Community editions install. ###
Community() {
    CopyFile $cfolder/settings_community.conf $cfolder/settings.conf
}

###  All starts in the Main function. ###
Main() {
    local progname="$(basename "$0")"           # for help and messages
    local Home=/home/liveuser                   # liveuser's home folder
    local log=$Home/endeavour-install.log       # install log
    local mode=""                               # one of: offline, online, sway, bspwm
    local cfolder=/etc/calamares                # folder for calamares configuration files

    # sets the value for $mode
    AskMode

    # echo "mode = $mode" ;  return   # TESTING !!!

    case "$mode" in
        online)    Online ;;
        offline)   Offline ;;
        community) Community ;;
    esac

    # finally: install with calamares
    InstallWithLogs
}

Main "$@"
